# Attack case for RepyArgumentError on negative offset.

# clean up if the file exists.
if "testfile.txt" in listfiles():
  removefile("testfile.txt")

# create a file
myfile=openfile("testfile.txt",True)

try:
  myfile.writeat("Hello", -1)
except RepyArgumentError:
  pass
except Exception:
  log("Unexpected Exception Raised!\n")
else:
  log("Should throw RepyArgumentError since a negative offset is passed to writeat()\n")

# Should not throw error on close()
try:
  myfile.close()
except Exception as e:
  log("Unexpected Exception thrown at file close!\n")
  log("Exception: ")
  log(e)
  log("\n")
