# This test case will test opening the same file twice
# clean up if the file exists.
if "testfile.txt" in listfiles():
  removefile("testfile.txt")

# create a file
myfile=openfile("testfile.txt",True)

# trying to reopen the same file
try:
   myfile=openfile("testfile.txt",True)
except FileInUseError:
   pass
else:
   log("ERROR: It should throw a FileInUseError error which is not being thrown here\n")

# Now close the file, this will write the content of writeat into file
myfile.close()
