"""
Author: Tom Zhang, tyz212

Description
    - Attempts to undo a change after a file is closed.
Objective
    - Cause the security layer to raise an error or exception
Note:
    - All "Fatal Error: Function 'LPFile.undo'" log outputs produced by the reference monitors are caused by this attack (attack case 6).
"""

FILENAME = "test.txt"
CREATE = True
WRITE_DATA = "Hello world"
WRITE_OFFSET = 0


def main():
    try:
        if FILENAME in listfiles():
            removefile(FILENAME)
        test_file = openfile(FILENAME, CREATE)
        
        test_file.writeat(WRITE_DATA, WRITE_OFFSET)
        test_file.close()

    except Exception as ex:
        pass

    else:
        try:
            # Should do nothing
            test_file.undo()
        except Exception as ex:
            log_success(str(ex))
            


if callfunc == "initialize":
    main()